### ISSUE TITLE
outputs ngCMatrix  by default.  would be better to output dgCMatrix by default

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/fastRG#15] opened 2020-03-07 11:54 UTC
> A = chung_lu(theta, avg_deg  = 10)
> ei = eigs(A, 3)
Error in UseMethod("eigs") : 
  no applicable method for 'eigs' applied to an object of class "c('ngCMatrix', 'CsparseMatrix', 'nsparseMatrix', 'generalMatrix', 'nCsparseMatrix', 'nMatrix', 'sparseMatrix', 'compMatrix', 'Matrix', 'mMatrix', 'Mnumeric', 'replValueSp')"
> str(A)
Formal class 'ngCMatrix' [package "Matrix"] with 5 slots
  ..@ i       : int [1:997665] 2340 4037 11685 14834 21592 35355 38145 54212 56915 61410 ...
  ..@ p       : int [1:100001] 0 15 20 21 22 29 31 50 52 53 ...
  ..@ Dim     : int [1:2] 100000 100000
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ factors : list()
> A = A+0
> str(A)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:997665] 2340 4037 11685 14834 21592 35355 38145 54212 56915 61410 ...
  ..@ p       : int [1:100001] 0 15 20 21 22 29 31 50 52 53 ...
  ..@ Dim     : int [1:2] 100000 100000
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ x       : num [1:997665] 1 1 1 1 1 1 1 1 1 1 ...
  ..@ factors : list()
> ei = eigs(A, 3)
>

**Comment by alexpghayes** [comment] 2020-04-09 21:04
Note (to self): type stability (regardless of type) would be ideal. We can achieve this through a move to S3 classes.

**Comment by alexpghayes** [comment] 2020-04-10 20:59
Duplicate of #2. Resolved in the S3 branch, which I will push to CRAN soon.

**Closed by alexpghayes** 2020-04-10 20:59 UTC
